In [12]:
import pandas as pd
import numpy as np

df = pd.read_pickle('electronika_clean.pkl')

In [13]:
# Выручка / количество товаров

fs1 = df[['Phone_new', 'Order_ID', 'Quant', 'FullSum']] \
        .groupby(['Phone_new']) \
        .aggregate({'Order_ID': 'nunique', 'Quant': 'sum', 'FullSum': 'sum'}) \
        .rename(columns={'Order_ID': 'Чеки', 'Quant': 'Товары', 'FullSum': 'Выручка'})
fs1['Товар/чек'] = (fs1['Товары'] / fs1['Чеки']).apply(lambda x: round(x, 2))
fs1['Средний_чек'] = (fs1['Выручка'] / fs1['Чеки']).apply(lambda x: round(x, 2))

fs2 = df[df['Status_ID'] == 14][['Phone_new', 'Order_ID', 'Quant', 'FullSum']] \
        .groupby(['Phone_new']) \
        .aggregate({'Order_ID': 'nunique', 'Quant': 'sum', 'FullSum': 'sum'}) \
        .rename(columns={'Order_ID': 'Чеки_выкуп', 'Quant': 'Товары_выкуп', 'FullSum': 'Выручка_выкуп'})
fs2['Товар/чек_выкуп'] = (fs2['Товары_выкуп'] / fs2['Чеки_выкуп']).apply(lambda x: round(x, 2))
fs2['Средний_чек_выкуп'] = (fs2['Выручка_выкуп'] / fs2['Чеки_выкуп']).apply(lambda x: round(x, 2))


fs3 = fs1.join(fs2, how='left')
fs3.fillna(0, inplace=True)
fs3['процент_выкупа'] = fs3['Выручка_выкуп'] / fs3['Выручка']
fs3

,Чеки,Товары,Выручка,Товар/чек,Средний_чек,Чеки_выкуп,Товары_выкуп,Выручка_выкуп,Товар/чек_выкуп,Средний_чек_выкуп,процент_выкупа
Phone_new,,,,,,,,,,,
32565748-000000000,13,15.0,259458.0,1.15,19958.31,8.0,8.0,19757.0,1.0,2469.62,0.076147
32565748-535549565054 55,1,1.0,12430.0,1.00,12430.00,0.0,0.0,0.0,0.0,0.00,0.000000
32565750-575448565151 а,1,2.0,53198.0,2.00,53198.00,1.0,2.0,53198.0,2.0,53198.00,1.000000
32565750-575448565151 а5,1,1.0,1590.0,1.00,1590.00,1.0,1.0,1590.0,1.0,1590.00,1.000000
43553240-575054413251+75,7,7.0,48557.0,1.00,6936.71,2.0,2.0,10129.0,1.0,5064.50,0.208600
...,...,...,...,...,...,...,...,...,...,...,...
57505548-48535350504991,1,1.0,999.0,1.00,999.00,1.0,1.0,999.0,1.0,999.00,1.000000
57544955-51485756555597,1,1.0,7700.0,1.00,7700.00,0.0,0.0,0.0,0.0,0.00,0.000000
57555656-55575253555698,1,1.0,4040.0,1.00,4040.00,1.0,1.0,4040.0,1.0,4040.00,1.000000
57565352-52575050555092,1,1.0,1999.0,1.00,1999.00,1.0,1.0,1999.0,1.0,1999.00,1.000000
57565355-57554952485597,2,2.0,3879.0,1.00,1939.50,1.0,1.0,3080.0,1.0,3080.00,0.794019

In [14]:
# Остальные признаки

fs4 = df[['Phone_new', 'TN', 'Region', 'Area', 'Actions', 'Source']]
tn_values = df['TN'].value_counts().index
for col in tn_values:
    fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))

actions_values = df['Actions'].value_counts().index
actions_set = set()
for action in actions_values:
    values = action.split(',')
    for value in values:
        actions_set.add(value)

for col in list(actions_set):
    fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))

fs4.drop(columns=['TN', 'Region', 'Area', 'Actions', 'Source'], inplace=True)

fs4_agg = fs4.groupby(['Phone_new']).sum()

fs = fs3.join(fs4_agg)
fs.fillna(0, inplace=True)
fs

/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = (fs4['TN'] == col).apply(lambda x: int(x))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4[col] = fs4['Actions'].apply(lambda x: int(str(x).find(col) != -1))
/var/folders/bh/d932d5zj56z9_y_7lh3s66ndf1n4c9/T/ipykernel_23940/4254673185.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fs4.drop(columns=['TN', 'Region', 'Area', 'Actions', 'Source'], inplace=True)

,Чеки,Товары,Выручка,Товар/чек,Средний_чек,Чеки_выкуп,Товары_выкуп,Выручка_выкуп,Товар/чек_выкуп,Средний_чек_выкуп,...,Элитная техника,Инсталляция,"Хобби, досуг",НайдёшьДешевле,СкидкаНаТоварПоПромоСлову,БесплатнаяДоставкаНаСуммуКорзины,Подарки,СкидкаСуммойПроцентомСЛимитом,СкидкаНаКомплект,СкидкаДляСпособаОплаты
Phone_new,,,,,,,,,,,,,,,,,,,,,
32565748-000000000,13,15.0,259458.0,1.15,19958.31,8.0,8.0,19757.0,1.0,2469.62,...,0,0,0,0,0,0,0,1,0,0
32565748-535549565054 55,1,1.0,12430.0,1.00,12430.00,0.0,0.0,0.0,0.0,0.00,...,0,0,0,0,0,0,0,0,0,0
32565750-575448565151 а,1,2.0,53198.0,2.00,53198.00,1.0,2.0,53198.0,2.0,53198.00,...,0,0,0,0,0,0,0,0,0,0
32565750-575448565151 а5,1,1.0,1590.0,1.00,1590.00,1.0,1.0,1590.0,1.0,1590.00,...,0,0,0,0,0,0,0,0,0,0
43553240-575054413251+75,7,7.0,48557.0,1.00,6936.71,2.0,2.0,10129.0,1.0,5064.50,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57505548-48535350504991,1,1.0,999.0,1.00,999.00,1.0,1.0,999.0,1.0,999.00,...,0,0,0,0,0,0,0,0,0,0
57544955-51485756555597,1,1.0,7700.0,1.00,7700.00,0.0,0.0,0.0,0.0,0.00,...,0,0,0,0,0,1,0,1,0,0
57555656-55575253555698,1,1.0,4040.0,1.00,4040.00,1.0,1.0,4040.0,1.0,4040.00,...,0,0,0,0,0,0,0,0,0,0
57565352-52575050555092,1,1.0,1999.0,1.00,1999.00,1.0,1.0,1999.0,1.0,1999.00,...,0,0,0,0,0,0,0,1,0,0
57565355-57554952485597,2,2.0,3879.0,1.00,1939.50,1.0,1.0,3080.0,1.0,3080.00,...,0,0,0,0,0,0,0,0,0,0

In [15]:
for col in fs.columns:
    fs[col] = (fs[col] - fs[col].mean()) / fs[col].std()
fs

,Чеки,Товары,Выручка,Товар/чек,Средний_чек,Чеки_выкуп,Товары_выкуп,Выручка_выкуп,Товар/чек_выкуп,Средний_чек_выкуп,...,Элитная техника,Инсталляция,"Хобби, досуг",НайдёшьДешевле,СкидкаНаТоварПоПромоСлову,БесплатнаяДоставкаНаСуммуКорзины,Подарки,СкидкаСуммойПроцентомСЛимитом,СкидкаНаКомплект,СкидкаДляСпособаОплаты
Phone_new,,,,,,,,,,,,,,,,,,,,,
32565748-000000000,2.610266,2.112402,2.207227,-0.017330,0.166716,2.157993,1.875093,0.152012,0.142967,-0.253066,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,1.065276,-0.046178,-0.076653
32565748-535549565054 55,-0.072713,-0.099822,-0.065060,-0.060605,-0.023888,-0.258793,-0.277362,-0.173886,-0.957929,-0.356835,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,-0.241621,-0.046178,-0.076653
32565750-575448565151 а,-0.072713,0.058194,0.309945,0.227895,1.008286,0.043305,0.260751,0.703632,1.243863,1.878441,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,-0.241621,-0.046178,-0.076653
32565750-575448565151 а5,-0.072713,-0.099822,-0.164771,-0.060605,-0.298338,0.043305,-0.008306,-0.147658,0.142967,-0.290026,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,-0.241621,-0.046178,-0.076653
43553240-575054413251+75,1.268777,0.848274,0.267255,-0.060605,-0.162968,0.345404,0.260751,-0.006805,0.142967,-0.144035,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,-0.241621,-0.046178,-0.076653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57505548-48535350504991,-0.072713,-0.099822,-0.170208,-0.060605,-0.313301,0.043305,-0.008306,-0.157407,0.142967,-0.314859,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,-0.241621,-0.046178,-0.076653
57544955-51485756555597,-0.072713,-0.099822,-0.108568,-0.060605,-0.143643,-0.258793,-0.277362,-0.173886,-0.957929,-0.356835,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,0.980828,-0.045269,1.065276,-0.046178,-0.076653
57555656-55575253555698,-0.072713,-0.099822,-0.142235,-0.060605,-0.236308,0.043305,-0.008306,-0.107245,0.142967,-0.187082,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,-0.241621,-0.046178,-0.076653
57565352-52575050555092,-0.072713,-0.099822,-0.161009,-0.060605,-0.287982,0.043305,-0.008306,-0.140912,0.142967,-0.272841,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,1.065276,-0.046178,-0.076653
57565355-57554952485597,0.150869,0.058194,-0.143716,-0.060605,-0.289489,0.043305,-0.008306,-0.123080,0.142967,-0.227419,...,-0.006981,-0.00285,-0.00285,-0.063373,-0.057401,-0.323169,-0.045269,-0.241621,-0.046178,-0.076653

In [16]:
fs.reset_index().to_csv('features.csv', index=False)