In [27]:
import pandas as pd
import numpy as np
import math

df = pd.read_pickle('electronika_clean.pkl')
df

,Unnamed: 0,Order_ID,Email_new,Phone_new,Source,OrderDate,время,месяц,ChangeDate,DeliveryDate,...,Quant,RowPrice,RowDiscount,RowSum,Brand,TN,TK,NomFullPath,Week,Nom_ID
0,10,1303000511_TT,556669108109_lm16@gmail.com,55574953-52525755535375,Онлайн-Резерв.,2016-03-01,10:46:45.000,201603,2016-03-05 09:16:49.000,2016-03-01 00:00:00.000,...,1,2970,0,2970,Ника,Товары для дома,Хозтовары,Техника для дома/Техника для ухода за одеждой/...,9,90364
1,12,1303000512_TT,556669108109_lm16@gmail.com,55574953-52525755535375,Онлайн-Резерв.,2016-03-01,10:47:19.000,201603,2016-03-01 10:59:43.000,2016-03-01 00:00:00.000,...,1,19490,0,19490,DeLonghi,Мелкая бытовая техника,Приготовление пищи,Техника для кухни/Приготовление пищи/Мультиварки/,9,45673
2,14,1303000513_TT,666668112117_pu19@ya.ru,55575655-50555350534877,Онлайн-Резерв.,2016-03-11,16:06:56.000,201603,2016-03-11 20:11:18.000,2016-03-12 00:00:00.000,...,1,19990,0,19990,Samsung,ТВ-Аудио,Телевизоры LCD,"Телевизоры, аудио, видео/Телевизоры/LED телеви...",10,120757
3,16,1303000514_TT,666668112117_pu19@ya.ru,55575653-57485657505272,Онлайн-Резерв.,2016-03-15,18:13:33.000,201603,2016-03-15 18:17:35.000,2016-03-22 00:00:00.000,...,1,23680,0,23680,СМК,Мебель,Мягкая мебель,Мебель/Мягкая мебель/Диваны/Трехместные диваны/,11,264580
4,28,1303000520_TT,56666668112117_pu26@yanded.ru,55575449-54535553535073,Онлайн-Резерв.,2016-03-01,00:01:46.000,201603,2016-03-04 15:09:38.000,2016-03-02 00:00:00.000,...,1,2420,0,2420,HP,Аксессуары,Картриджи и бумага,"Компьютеры, ноутбуки, планшеты/Оргтехника/Расх...",9,76102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183067,357019,5898089_BX,6666449117_1u9@bk.ru,55574957-51495048515075,Онлайн-Резерв.,2016-04-30,23:51:37.000,201604,2016-05-03 12:55:07.000,2016-05-02 00:00:00.000,...,1,899,0,899,Saturn,Климат,Вентиляторы бытовые,Техника для дома/Климатическая техника/Кондици...,17,38755
183068,357021,5898095_BX,666661118109_vm27@yahoo.com,55575452-55554849505278,Онлайн-Резерв.,2016-04-30,23:54:03.000,201604,2016-05-04 19:43:40.000,2016-05-07 00:00:00.000,...,1,1090,0,1090,Case Logic,Аксессуары,Аксессуары для фото/видео,Фото- и видеотехника/Аксессуары для фото и вид...,17,31908
183069,357023,5898099_BX,3110116_nt16@pisem.net,55574948-50554849554878,Онлайн-Резерв.,2016-04-30,23:56:02.000,201604,2016-05-01 11:57:42.000,2016-05-08 00:00:00.000,...,1,6859,0,6859,ELIKOR,Крупная бытовая техника,Встраиваемая техника,Встраиваемая техника/Вытяжки/,17,140459
183070,357024,5898102_BX,55666665102117_fu13@list.ru,55575648-51484956545071,Онлайн-Резерв.,2016-04-30,23:56:38.000,201604,2016-05-06 20:18:49.000,2016-05-05 00:00:00.000,...,1,9120,0,9120,FORWARD,Спорт и активный отдых,Велосипеды и аксессуары,Товары для спорта и отдыха/Велосипеды и аксесс...,17,295956
183071,357027,5898108_BX,566102117_fu20@rambler.ru,55574851-54534948525271,Онлайн-Резерв.,2016-04-30,23:57:42.000,201604,2016-05-09 09:10:30.000,2016-05-04 00:00:00.000,...,1,900,0,900,Hasbro,Детские товары,Игрушки,Детские товары/Игрушки/Творчество и развитие р...,17,123514

In [28]:
df[df['TN'] == 'Крупная бытовая техника']

,Unnamed: 0,Order_ID,Email_new,Phone_new,Source,OrderDate,время,месяц,ChangeDate,DeliveryDate,...,Quant,RowPrice,RowDiscount,RowSum,Brand,TN,TK,NomFullPath,Week,Nom_ID
5,30,1303000521_TT,551120117_xu11@bk.ru,55574954-53565052504871,Онлайн-Резерв.,2016-03-01,00:02:17.000,201603,2016-03-03 15:03:50.000,2016-03-02 00:00:00.000,...,1,10999,2000,8999,Darina,Крупная бытовая техника,Плиты,Техника для кухни/Крупная бытовая техника/Плит...,9,93780
32,79,1303000542_TT,666663109117_mu12@np-sr.ru,55574951-505356545052725,Онлайн-Резерв.,2016-03-01,00:27:46.000,201603,2016-03-11 13:29:59.000,2016-03-02 00:00:00.000,...,1,11039,552,10487,Darina,Крупная бытовая техника,Плиты,Техника для кухни/Крупная бытовая техника/Плит...,9,93780
40,95,1303000550_TT,101117_eu13@ya.ru,55574954-50525155575079,Онлайн-Резерв.,2016-03-01,00:35:03.000,201603,2016-03-13 09:05:40.000,2016-03-07 00:00:00.000,...,1,27970,0,27970,Samsung,Крупная бытовая техника,Встраиваемая техника,Встраиваемая техника/Встраиваемые посудомоечны...,9,74995
46,106,1303000555_TT,552117_4u12@e1.ru,55575655-57485250515072,Онлайн-Резерв.,2016-03-01,00:38:32.000,201603,2016-03-03 12:59:19.000,2016-03-03 00:00:00.000,...,1,7869,0,7869,Лысьва,Крупная бытовая техника,Плиты,Техника для кухни/Крупная бытовая техника/Плит...,9,204924
51,116,1303000560_TT,598117_bu22@yandex.ruu,55575054-48525649485173,Онлайн-Резерв.,2016-03-01,00:43:37.000,201603,2016-03-04 20:15:38.000,2016-03-03 00:00:00.000,...,1,17999,0,17999,Hotpoint-Ariston,Крупная бытовая техника,Стиральные машины,Техника для дома/Стиральные и сушильные машины...,9,12099
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183026,356940,5897989_ES,599117_cu15@live.ru,55575653-57525452545377,Онлайн-Резерв.,2016-04-30,23:12:45.000,201604,2016-05-14 09:03:53.000,2016-05-08 00:00:00.000,...,1,20990,0,20990,Korting,Крупная бытовая техника,Посудомоечные машины,Техника для кухни/Крупная бытовая техника/Посу...,17,77767
183027,356942,5897990_BX,599117_cu15@live.ru,55575653-57525452545377,Онлайн-Резерв.,2016-04-30,23:12:46.000,201604,2016-05-14 09:03:51.000,2016-05-08 00:00:00.000,...,1,20990,0,20990,Korting,Крупная бытовая техника,Посудомоечные машины,Техника для кухни/Крупная бытовая техника/Посу...,17,77767
183031,356950,5897998_BX,566666454117_6u17@rambler.ru,55574852-535352505756775,Онлайн-Резерв.,2016-04-30,23:15:31.000,201604,2016-05-01 16:00:04.000,2016-05-10 00:00:00.000,...,1,29609,0,29609,Bosch,Крупная бытовая техника,Встраиваемая техника,Встраиваемая техника/Встраиваемые духовые шкаф...,17,97418
183065,357014,5898081_BX,5668107117_ku16@tg14.ru,55575155-54515157565779,Онлайн-Резерв.,2016-04-30,23:46:32.000,201604,2016-05-01 21:02:15.000,2016-05-02 00:00:00.000,...,1,20160,1300,18860,Gorenje,Крупная бытовая техника,Встраиваемая техника,Встраиваемая техника/Встраиваемые варочные пан...,17,146255
183069,357023,5898099_BX,3110116_nt16@pisem.net,55574948-50554849554878,Онлайн-Резерв.,2016-04-30,23:56:02.000,201604,2016-05-01 11:57:42.000,2016-05-08 00:00:00.000,...,1,6859,0,6859,ELIKOR,Крупная бытовая техника,Встраиваемая техника,Встраиваемая техника/Вытяжки/,17,140459

In [29]:
cl = pd.read_csv('clustering_results_1.csv')
cl

,Unnamed: 0,Phone_new,Чеки,Товары,Выручка,Средний_чек,Товары_выкуп,Выручка_выкуп,Товар/чек_выкуп,процент_выкупа,...,Подарки,СкидкаДляСпособаОплаты,НайдёшьДешевле,СкидкаНаКомплект,СкидкаСуммойПроцентомСЛимитом,Колл-центр,Сайт,Терминал,Большой город,cluster
0,0,32565748-000000000,13,15,259458.0,19958.31,8.0,19757.0,1.0,0.076147,...,0,0,0,0,1,0,0,15,14,2
1,1,32565748-535549565054 55,1,1,12430.0,12430.00,0.0,0.0,0.0,0.000000,...,0,0,0,0,0,0,0,0,1,0
2,2,32565750-575448565151 а,1,2,53198.0,53198.00,2.0,53198.0,2.0,1.000000,...,0,0,0,0,0,2,0,0,0,5
3,3,32565750-575448565151 а5,1,1,1590.0,1590.00,1.0,1590.0,1.0,1.000000,...,0,0,0,0,0,0,0,0,1,0
4,4,43553240-575054413251+75,7,7,48557.0,6936.71,2.0,10129.0,1.0,0.208600,...,0,0,0,0,0,0,0,0,7,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123107,123107,57505548-48535350504991,1,1,999.0,999.00,1.0,999.0,1.0,1.000000,...,0,0,0,0,0,0,1,0,1,0
123108,123108,57544955-51485756555597,1,1,7700.0,7700.00,0.0,0.0,0.0,0.000000,...,0,0,0,0,1,0,0,0,0,0
123109,123109,57555656-55575253555698,1,1,4040.0,4040.00,1.0,4040.0,1.0,1.000000,...,0,0,0,0,0,0,0,0,1,0
123110,123110,57565352-52575050555092,1,1,1999.0,1999.00,1.0,1999.0,1.0,1.000000,...,0,0,0,0,1,0,0,0,1,0
123111,123111,57565355-57554952485597,2,2,3879.0,1939.50,1.0,3080.0,1.0,0.794019,...,0,0,0,0,0,0,0,0,0,0

In [30]:
join = df.join(cl[['Phone_new', 'cluster']].set_index('Phone_new'), on='Phone_new')
join['cluster'].value_counts()

cluster
0    132143
5     31926
2     10321
4      5271
3      2753
1       611
6        47
Name: count, dtype: int64

In [31]:
actions_values = join['Actions'].value_counts().index
actions_set = set()
for action in actions_values:
    values = action.split(',')
    for value in values:
        actions_set.add(value)

for col in list(actions_set):
    join[col] = join['Actions'].apply(lambda x: int(str(x).find(col) != -1))
join

,Unnamed: 0,Order_ID,Email_new,Phone_new,Source,OrderDate,время,месяц,ChangeDate,DeliveryDate,...,Week,Nom_ID,cluster,БесплатнаяДоставкаНаСуммуКорзины,СкидкаНаКомплект,СкидкаСуммойПроцентомСЛимитом,СкидкаДляСпособаОплаты,СкидкаНаТоварПоПромоСлову,Подарки,НайдёшьДешевле
0,10,1303000511_TT,556669108109_lm16@gmail.com,55574953-52525755535375,Онлайн-Резерв.,2016-03-01,10:46:45.000,201603,2016-03-05 09:16:49.000,2016-03-01 00:00:00.000,...,9,90364,2,0,0,0,0,0,0,0
1,12,1303000512_TT,556669108109_lm16@gmail.com,55574953-52525755535375,Онлайн-Резерв.,2016-03-01,10:47:19.000,201603,2016-03-01 10:59:43.000,2016-03-01 00:00:00.000,...,9,45673,2,0,0,0,0,0,0,0
2,14,1303000513_TT,666668112117_pu19@ya.ru,55575655-50555350534877,Онлайн-Резерв.,2016-03-11,16:06:56.000,201603,2016-03-11 20:11:18.000,2016-03-12 00:00:00.000,...,10,120757,0,1,0,0,0,0,0,0
3,16,1303000514_TT,666668112117_pu19@ya.ru,55575653-57485657505272,Онлайн-Резерв.,2016-03-15,18:13:33.000,201603,2016-03-15 18:17:35.000,2016-03-22 00:00:00.000,...,11,264580,0,1,0,0,0,0,0,0
4,28,1303000520_TT,56666668112117_pu26@yanded.ru,55575449-54535553535073,Онлайн-Резерв.,2016-03-01,00:01:46.000,201603,2016-03-04 15:09:38.000,2016-03-02 00:00:00.000,...,9,76102,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183067,357019,5898089_BX,6666449117_1u9@bk.ru,55574957-51495048515075,Онлайн-Резерв.,2016-04-30,23:51:37.000,201604,2016-05-03 12:55:07.000,2016-05-02 00:00:00.000,...,17,38755,0,0,0,0,0,0,0,0
183068,357021,5898095_BX,666661118109_vm27@yahoo.com,55575452-55554849505278,Онлайн-Резерв.,2016-04-30,23:54:03.000,201604,2016-05-04 19:43:40.000,2016-05-07 00:00:00.000,...,17,31908,0,0,0,0,0,0,0,0
183069,357023,5898099_BX,3110116_nt16@pisem.net,55574948-50554849554878,Онлайн-Резерв.,2016-04-30,23:56:02.000,201604,2016-05-01 11:57:42.000,2016-05-08 00:00:00.000,...,17,140459,0,1,0,0,0,0,0,0
183070,357024,5898102_BX,55666665102117_fu13@list.ru,55575648-51484956545071,Онлайн-Резерв.,2016-04-30,23:56:38.000,201604,2016-05-06 20:18:49.000,2016-05-05 00:00:00.000,...,17,295956,0,0,0,0,0,0,0,0
183071,357027,5898108_BX,566102117_fu20@rambler.ru,55574851-54534948525271,Онлайн-Резерв.,2016-04-30,23:57:42.000,201604,2016-05-09 09:10:30.000,2016-05-04 00:00:00.000,...,17,123514,0,0,0,0,0,0,0,0

In [34]:
join['QuantAction'] = join['Quant'] * join['СкидкаСуммойПроцентомСЛимитом']
action = join[join['TN'] == 'Крупная бытовая техника'][['OrderDate', 'QuantAction']].groupby(['OrderDate']).sum()
action.head(60)

            QuantAction
OrderDate
2016-03-01           63
2016-03-02           47
2016-03-03           60
2016-03-04           56
2016-03-05          445
2016-03-06          414
2016-03-07          402
2016-03-08          313
2016-03-09           34
2016-03-10           37
2016-03-11           38
2016-03-12           55
2016-03-13           46
2016-03-14           46
2016-03-15            0
2016-03-16            0
2016-03-17            1
2016-03-18            2
2016-03-19            2
2016-03-20            1
2016-03-21            1
2016-03-22            5
2016-03-23            0
2016-03-24            0
2016-03-25            2
2016-03-26            1
2016-03-27            0
2016-03-28            0
2016-03-29            2
2016-03-30            0
2016-03-31            3
2016-04-01            0
2016-04-02            0
2016-04-03            1
2016-04-04            0
2016-04-05            0
2016-04-06            0
2016-04-07            1
2016-04-08            0
2016-04-09           63
2016-04-10           87
2016-04-11           36
2016-04-12           32
2016-04-13           23
2016-04-14           21
2016-04-15           11
2016-04-16           68
2016-04-17           90
2016-04-18            2
2016-04-19            1
2016-04-20            0
2016-04-21            1
2016-04-22            0
2016-04-23            1
2016-04-24            7
2016-04-25            9
2016-04-26            7
2016-04-27            2
2016-04-28            0
2016-04-29            9

In [33]:
cluster_0_sales = join[(join['TN'] == 'Крупная бытовая техника') & (join['cluster'] == 0)]
total_sales = join[join['cluster'] == 0][['Quant', 'OrderDate']].groupby(['OrderDate']).sum()
cluster_0_sales_grouped = cluster_0_sales[['Quant', 'OrderDate']].groupby(['OrderDate']).sum()
cluster_0_sales_grouped_join = cluster_0_sales_grouped.join(total_sales, rsuffix='_total')
cluster_0_sales_grouped_join

            Quant  Quant_total
OrderDate
2016-03-01    202         2490
2016-03-02    234         2988
2016-03-03    185         3038
2016-03-04    186         2556
2016-03-05    337         3294
...           ...          ...
2016-04-26    235         2365
2016-04-27    220         2271
2016-04-28    180         1985
2016-04-29    159         1987
2016-04-30    181         1776

[61 rows x 2 columns]

In [21]:
cluster_5_sales = join[(join['TN'] == 'Крупная бытовая техника') & (join['cluster'] == 5)]
total_sales = join[join['cluster'] == 5][['Quant', 'OrderDate']].groupby(['OrderDate']).sum()
cluster_5_sales_grouped = cluster_5_sales[['Quant', 'OrderDate']].groupby(['OrderDate']).sum()
cluster_5_sales_grouped_join = cluster_5_sales_grouped.join(total_sales, rsuffix='_total')
cluster_5_sales_grouped_join

            Quant  Quant_total
OrderDate
2016-03-01    164          568
2016-03-02    148          644
2016-03-03    140          609
2016-03-04    133          650
2016-03-05    228          687
...           ...          ...
2016-04-26    150          517
2016-04-27    144          498
2016-04-28    138          568
2016-04-29    104          465
2016-04-30    107          455

[61 rows x 2 columns]

In [ ]:
cluster_0_sales['']