In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel('electronika_clean.xlsx')
df

,Unnamed: 0,Order_ID,Email_new,Phone_new,Source,OrderDate,время,месяц,ChangeDate,DeliveryDate,...,Quant,RowPrice,RowDiscount,RowSum,Brand,TN,TK,NomFullPath,Week,Nom_ID
0,2,1303000509_TT,55666668105117_iu29@yandex.ru,55485656-57565656575275,Онлайн-Резерв.,2016-03-30,08:46:30.000,201603,2016-03-30 09:31:57.000,2016-04-06 00:00:00.000,...,1,35999,0,35999,Samsung,ТВ-Аудио,Телевизоры LCD,"Телевизоры, аудио, видео/Телевизоры/Smart теле...",13,95567
1,4,1303000510_TT,55666668105117_iu29@yandex.ru,55485656-57565656575275,Онлайн-Резерв.,2016-03-30,11:22:51.000,201603,2016-03-30 11:24:32.000,2016-04-06 00:00:00.000,...,2,3990,0,7980,NaN,NaN,NaN,Установка и настройка техники/Установка и наст...,13,2748
2,5,1303000510_TT,55666668105117_iu29@yandex.ru,55485656-57565656575275,Онлайн-Резерв.,2016-03-30,11:22:51.000,201603,2016-03-30 11:24:32.000,2016-04-06 00:00:00.000,...,2,4490,0,8980,NaN,NaN,NaN,Установка и настройка техники/Установка и наст...,13,7874
3,7,1303000510_TT,55666668105117_iu29@yandex.ru,55485656-57565656575275,Онлайн-Резерв.,2016-03-30,11:22:51.000,201603,2016-03-30 11:24:32.000,2016-04-06 00:00:00.000,...,2,32999,0,65998,Sony,ТВ-Аудио,Телевизоры LCD,"Телевизоры, аудио, видео/Телевизоры/Smart теле...",13,99485
4,8,1303000510_TT,55666668105117_iu29@yandex.ru,55485656-57565656575275,Онлайн-Резерв.,2016-03-30,11:22:51.000,201603,2016-03-30 11:24:32.000,2016-04-06 00:00:00.000,...,2,999,0,1998,РЭМО,Аксессуары,Аксессуары ТВ-Аудио,"Телевизоры, аудио, видео/Аксессуары для ТВ/Ант...",13,20709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187747,357019,5898089_BX,6666449117_1u9@bk.ru,55574957-51495048515075,Онлайн-Резерв.,2016-04-30,23:51:37.000,201604,2016-05-03 12:55:07.000,2016-05-02 00:00:00.000,...,1,899,0,899,Saturn,Климат,Вентиляторы бытовые,Техника для дома/Климатическая техника/Кондици...,17,38755
187748,357021,5898095_BX,666661118109_vm27@yahoo.com,55575452-55554849505278,Онлайн-Резерв.,2016-04-30,23:54:03.000,201604,2016-05-04 19:43:40.000,2016-05-07 00:00:00.000,...,1,1090,0,1090,Case Logic,Аксессуары,Аксессуары для фото/видео,Фото- и видеотехника/Аксессуары для фото и вид...,17,31908
187749,357023,5898099_BX,3110116_nt16@pisem.net,55574948-50554849554878,Онлайн-Резерв.,2016-04-30,23:56:02.000,201604,2016-05-01 11:57:42.000,2016-05-08 00:00:00.000,...,1,6859,0,6859,ELIKOR,Крупная бытовая техника,Встраиваемая техника,Встраиваемая техника/Вытяжки/,17,140459
187750,357024,5898102_BX,55666665102117_fu13@list.ru,55575648-51484956545071,Онлайн-Резерв.,2016-04-30,23:56:38.000,201604,2016-05-06 20:18:49.000,2016-05-05 00:00:00.000,...,1,9120,0,9120,FORWARD,Спорт и активный отдых,Велосипеды и аксессуары,Товары для спорта и отдыха/Велосипеды и аксесс...,17,295956
187751,357027,5898108_BX,566102117_fu20@rambler.ru,55574851-54534948525271,Онлайн-Резерв.,2016-04-30,23:57:42.000,201604,2016-05-09 09:10:30.000,2016-05-04 00:00:00.000,...,1,900,0,900,Hasbro,Детские товары,Игрушки,Детские товары/Игрушки/Творчество и развитие р...,17,123514

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187752 entries, 0 to 187751
Data columns (total 38 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    187752 non-null  int64
 1   Order_ID      187752 non-null  object
 2   Email_new     187752 non-null  object
 3   Phone_new     187752 non-null  object
 4   Source        187752 non-null  object
 5   OrderDate     187752 non-null  datetime64[ns]
 6   время         187752 non-null  object
 7   месяц         187752 non-null  int64
 8   ChangeDate    187752 non-null  object
 9   DeliveryDate  187752 non-null  object
 10  PaymentDate   187752 non-null  object
 11  Status        187752 non-null  object
 12  Status_ID     187752 non-null  int64
 13  OneClick      187752 non-null  int64
 14  CancelReason  66835 non-null   object
 15  Actions       52395 non-null   object
 16  DeliveryType  183711 non-null  object
 17  PaymentType   187752 non-null  object
 18  Region        187751 non-null  object
 19  Area          186911 non-null  object
 20  Store_ID      187752 non-null  int64
 21  FullSum       187752 non-null  float64
 22  Discount      187752 non-null  float64
 23  IM_Rozn_Sum   187752 non-null  float64
 24  Row_ID        187752 non-null  int64
 25  Articul       187752 non-null  int64
 26  Nom_Name      187742 non-null  object
 27  NomGroup      187752 non-null  object
 28  Quant         187752 non-null  int64
 29  RowPrice      187752 non-null  int64
 30  RowDiscount   187752 non-null  int64
 31  RowSum        187752 non-null  int64
 32  Brand         187015 non-null  object
 33  TN            187059 non-null  object
 34  TK            187059 non-null  object
 35  NomFullPath   187752 non-null  object
 36  Week          187752 non-null  int64
 37  Nom_ID        187752 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(13), object(21)
memory usage: 54.4+ MB

In [3]:
all = df[['месяц', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['месяц']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
all['Avg goods'] = (all['Quant'] / all['Order_ID']).apply(lambda x: round(x, 2))
all['Avg order'] = (all['RowSum'] / all['Order_ID']).apply(lambda x: round(x, 2))
all['Avg client'] = (all['RowSum'] / all['Phone_new']).apply(lambda x: round(x, 2))
all.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

total = df[['RowSum', 'Order_ID', 'Phone_new', 'Quant']] \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
total_dict = {
    'RowSum': [total.iloc[0]],
    'Order_ID': [total.iloc[1]],
    'Phone_new': [total.iloc[2]],
    'Quant': [total.iloc[3]]
}
total_df = pd.DataFrame().from_dict(total_dict)
total_df
total_df['Avg goods'] = (total_df['Quant'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg order'] = (total_df['RowSum'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg client'] = (total_df['RowSum'] / total_df['Phone_new']).apply(lambda x: round(x, 2))
total_df.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)
all = pd.concat([all, total_df], axis=0)


sold = df[df['Status_ID'] == 14][['месяц', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['месяц']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})

sold['Avg goods'] = (sold['Quant'] / sold['Order_ID']).apply(lambda x: round(x, 2))
sold['Avg order'] = (sold['RowSum'] / sold['Order_ID']).apply(lambda x: round(x, 2))
sold['Avg client'] = (sold['RowSum'] / sold['Phone_new']).apply(lambda x: round(x, 2))
sold.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

total = df[df['Status_ID'] == 14][['RowSum', 'Order_ID', 'Phone_new', 'Quant']] \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
total_dict = {
    'RowSum': [total.iloc[0]],
    'Order_ID': [total.iloc[1]],
    'Phone_new': [total.iloc[2]],
    'Quant': [total.iloc[3]]
}
total_df = pd.DataFrame().from_dict(total_dict)
total_df
total_df['Avg goods'] = (total_df['Quant'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg order'] = (total_df['RowSum'] / total_df['Order_ID']).apply(lambda x: round(x, 2))
total_df['Avg client'] = (total_df['RowSum'] / total_df['Phone_new']).apply(lambda x: round(x, 2))
total_df.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)
sold = pd.concat([sold, total_df], axis=0)

In [4]:
all

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
201603,943796109,84974,66408,103979,1.22,11106.88,14212.08
201604,870470336,78195,61057,96940,1.24,11132.05,14256.68
0,1814266445,163168,123133,200919,1.23,11119.01,14734.20

In [5]:
sold

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
201603,525588675,54486,47816,64986,1.19,9646.31,10991.90
201604,488240415,50996,44214,61948,1.21,9574.09,11042.67
0,1013829090,105482,89554,126934,1.20,9611.39,11320.87

In [6]:
(100.0 * sold / all).apply(lambda x: round(x, 2))

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
201603,55.69,64.12,72.00,62.50,97.54,86.85,77.34
201604,56.09,65.22,72.41,63.90,97.58,86.00,77.46
0,55.88,64.65,72.73,63.18,97.56,86.44,76.83

In [7]:
all_by_category = df[['TN', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TN']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
all_by_category['Avg goods'] = (all_by_category['Quant'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg order'] = (all_by_category['RowSum'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg client'] = (all_by_category['RowSum'] / all_by_category['Phone_new']).apply(lambda x: round(x, 2))
all_by_category.sort_values(by='RowSum', ascending=False, inplace=True)
all_by_category.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

sold_by_category = df[df['Status_ID'] == 14][['TN', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TN']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})

sold_by_category['Avg goods'] = (sold_by_category['Quant'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg order'] = (sold_by_category['RowSum'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg client'] = (sold_by_category['RowSum'] / sold_by_category['Phone_new']).apply(lambda x: round(x, 2))
sold_by_category.sort_values(by='RowSum', ascending=False, inplace=True)
sold_by_category.rename(columns={'RowSum': 'Выручка, руб', 'Phone_new': 'Количество уникальных клиентов', 'Quant': 'Количество товаров', 'Order_ID': 'Количество чеков', 'Avg goods': 'Среднее количество', 'Avg order': 'Cредний чек, руб', 'Avg client': 'Ценность клиента'}, inplace=True)

In [8]:
all_by_category

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
TN,,,,,,,
Крупная бытовая техника,570168814,26998,19735,29906,1.11,21118.93,28891.25
Цифровая Техника,373347414,21718,18202,23411,1.08,17190.69,20511.34
ТВ-Аудио,253972111,11427,8711,13023,1.14,22225.62,29155.33
Мелкая бытовая техника,205225394,35632,28948,40080,1.12,5759.58,7089.45
Сделай сам,111640411,14830,12489,18845,1.27,7528.01,8939.10
Спорт и активный отдых,104752511,14072,11375,19315,1.37,7444.04,9209.01
Детские товары,78621645,12087,10093,13838,1.14,6504.65,7789.72
Мебель,35357064,7173,6081,9101,1.27,4929.19,5814.35
Климат,31854653,3354,2886,4344,1.30,9497.51,11037.65
Аксессуары,28600466,14262,12121,17705,1.24,2005.36,2359.58
Товары для дома,12783108,6441,5343,9365,1.45,1984.65,2392.50
"Игры, софт и развлечения",4695722,663,602,828,1.25,7082.54,7800.20
Услуги,380069,178,129,336,1.89,2135.22,2946.27
Элитная техника,304308,6,6,6,1.00,50718.00,50718.00
Автотовары,193460,85,74,86,1.01,2276.00,2614.32
Инсталляция,6270,1,1,30,30.00,6270.00,6270.00
"Хобби, досуг",35,1,1,1,1.00,35.00,35.00

In [9]:
sold_by_category

,"Выручка, руб",Количество чеков,Количество уникальных клиентов,Количество товаров,Среднее количество,"Cредний чек, руб",Ценность клиента
TN,,,,,,,
Крупная бытовая техника,357992093,17880,14810,19639,1.10,20021.93,24172.32
Цифровая Техника,148830063,11696,10923,12418,1.06,12724.87,13625.38
ТВ-Аудио,134971296,6921,5823,7184,1.04,19501.70,23179.00
Мелкая бытовая техника,128967057,24588,21857,26413,1.07,5245.12,5900.49
Сделай сам,67270126,9914,9183,12659,1.28,6785.37,7325.51
Спорт и активный отдых,58616632,8749,8124,11525,1.32,6699.81,7215.24
Детские товары,44787166,7469,7100,8464,1.13,5996.41,6308.05
Мебель,24681767,5278,5019,6678,1.27,4676.35,4917.67
Климат,18333422,2257,2157,2711,1.20,8122.92,8499.50
Аксессуары,18017776,9803,9015,11735,1.20,1837.99,1998.64
Товары для дома,8452294,4485,4090,6403,1.43,1884.57,2066.58
"Игры, софт и развлечения",1263014,370,352,414,1.12,3413.55,3588.11
Услуги,150433,80,64,171,2.14,1880.41,2350.52
Элитная техника,139878,3,3,3,1.00,46626.00,46626.00
Автотовары,91658,52,51,53,1.02,1762.65,1797.22
"Хобби, досуг",35,1,1,1,1.00,35.00,35.00

In [10]:
join = all_by_category.join(sold_by_category, how='left', rsuffix='_sold')
join['Доля выкупа (выручка)'] = (100.0 * join['Выручка, руб_sold'] / join['Выручка, руб']).apply(lambda x : round(x, 2))
join['Доля выкупа (количество товаров)'] = (100.0 * join['Количество товаров_sold'] / join['Количество товаров']).apply(lambda x : round(x, 2))

In [11]:
join[['Выручка, руб', 'Выручка, руб_sold', 'Доля выкупа (выручка)', 'Количество товаров', 'Количество товаров_sold', 'Доля выкупа (количество товаров)']]

,"Выручка, руб","Выручка, руб_sold",Доля выкупа (выручка),Количество товаров,Количество товаров_sold,Доля выкупа (количество товаров)
TN,,,,,,
Крупная бытовая техника,570168814,357992093.0,62.79,29906,19639.0,65.67
Цифровая Техника,373347414,148830063.0,39.86,23411,12418.0,53.04
ТВ-Аудио,253972111,134971296.0,53.14,13023,7184.0,55.16
Мелкая бытовая техника,205225394,128967057.0,62.84,40080,26413.0,65.90
Сделай сам,111640411,67270126.0,60.26,18845,12659.0,67.17
Спорт и активный отдых,104752511,58616632.0,55.96,19315,11525.0,59.67
Детские товары,78621645,44787166.0,56.97,13838,8464.0,61.16
Мебель,35357064,24681767.0,69.81,9101,6678.0,73.38
Климат,31854653,18333422.0,57.55,4344,2711.0,62.41
Аксессуары,28600466,18017776.0,63.00,17705,11735.0,66.28
Товары для дома,12783108,8452294.0,66.12,9365,6403.0,68.37
"Игры, софт и развлечения",4695722,1263014.0,26.90,828,414.0,50.00
Услуги,380069,150433.0,39.58,336,171.0,50.89
Элитная техника,304308,139878.0,45.97,6,3.0,50.00
Автотовары,193460,91658.0,47.38,86,53.0,61.63
Инсталляция,6270,NaN,NaN,30,NaN,NaN
"Хобби, досуг",35,35.0,100.00,1,1.0,100.00

In [12]:
all_by_category = df[['TK', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TK']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})
all_by_category['Avg goods'] = (all_by_category['Quant'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg order'] = (all_by_category['RowSum'] / all_by_category['Order_ID']).apply(lambda x: round(x, 2))
all_by_category['Avg client'] = (all_by_category['RowSum'] / all_by_category['Phone_new']).apply(lambda x: round(x, 2))
all_by_category.sort_values(by='RowSum', ascending=False, inplace=True)

sold_by_category = df[df['Status_ID'] == 14][['TK', 'RowSum', 'Order_ID', 'Phone_new', 'Quant']]\
    .groupby(['TK']) \
    .aggregate({'RowSum': 'sum', 'Order_ID': 'nunique', 'Phone_new': 'nunique', 'Quant': 'sum'})

sold_by_category['Avg goods'] = (sold_by_category['Quant'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg order'] = (sold_by_category['RowSum'] / sold_by_category['Order_ID']).apply(lambda x: round(x, 2))
sold_by_category['Avg client'] = (sold_by_category['RowSum'] / sold_by_category['Phone_new']).apply(lambda x: round(x, 2))
sold_by_category.sort_values(by='RowSum', ascending=False, inplace=True)

join = all_by_category.join(sold_by_category, how='left', rsuffix='_sold')
join['Доля выкупа (выручка)'] = (100.0 * join['RowSum_sold'] / join['RowSum']).apply(lambda x : round(x, 2))
join['Доля выкупа (количество товаров)'] = (100.0 * join['Quant_sold'] / join['Quant']).apply(lambda x : round(x, 2))
join.sort_values(by='RowSum', ascending=False, inplace=True)
join.rename(
    columns={
        'RowSum': 'Revenue total',
        'Order_ID': 'Orders total',
        'Phone_new': 'Clients total',
        'Quant': 'Goods total',
        'Avg order': 'Average bill total',
        'RowSum_sold': 'Revenue redeemed',
        'Доля выкупа (выручка)': 'Revenue redeemability',
        'Quant_sold': 'Goods redeemed',
        'Доля выкупа (количество товаров)': 'Goods redeemability'
    },
    inplace=True
)

join.head(20)

,Revenue total,Orders total,Clients total,Goods total,Avg goods,Average bill total,Avg client,Revenue redeemed,Order_ID_sold,Phone_new_sold,Goods redeemed,Avg goods_sold,Avg order_sold,Avg client_sold,Revenue redeemability,Goods redeemability
TK,,,,,,,,,,,,,,,,
Телевизоры LCD,226948918,7478,5382,7767,1.04,30348.88,42168.14,120590672.0,4485.0,3541.0,4595.0,1.02,26887.55,34055.54,53.14,59.16
Мобильные средства связи,202208122,10668,9093,11273,1.06,18954.64,22237.78,66398080.0,4956.0,4732.0,5217.0,1.05,13397.51,14031.72,32.84,46.28
Холодильное оборудование,191429362,7807,6152,8063,1.03,24520.22,31116.61,119899953.0,5215.0,4586.0,5337.0,1.02,22991.36,26144.78,62.63,66.19
Встраиваемая техника,183478346,9323,6855,10821,1.16,19680.18,26765.62,115362638.0,6140.0,5178.0,7099.0,1.16,18788.70,22279.38,62.88,65.60
Стиральные машины,119682526,5608,4274,5727,1.02,21341.39,28002.46,73728741.0,3601.0,3080.0,3629.0,1.01,20474.52,23937.90,61.60,63.37
Приготовление пищи,98155050,18730,15628,21173,1.13,5240.53,6280.72,59748877.0,12932.0,11814.0,13822.0,1.07,4620.23,5057.46,60.87,65.28
Компьютеры портативные,72251257,2118,1709,2214,1.05,34112.96,42276.92,30364053.0,961.0,858.0,991.0,1.03,31596.31,35389.34,42.03,44.76
Прогулки и путешествие,62409474,7091,5912,7616,1.07,8801.22,10556.41,33886944.0,4020.0,3918.0,4203.0,1.05,8429.59,8649.04,54.30,55.19
Плиты,60935209,4531,3836,4653,1.03,13448.51,15885.09,39705968.0,3128.0,2935.0,3180.0,1.02,12693.72,13528.44,65.16,68.34
Уход за домом,60059890,7063,5815,7569,1.07,8503.45,10328.44,37985089.0,4805.0,4279.0,4974.0,1.04,7905.33,8877.09,63.25,65.72
Силовая и садовая техника,54665338,5341,4650,6149,1.15,10235.04,11755.99,31464543.0,3391.0,3261.0,3844.0,1.13,9278.84,9648.74,57.56,62.51
Велосипеды и аксессуары,51469096,4293,3607,4570,1.06,11989.07,14269.23,26334670.0,2411.0,2341.0,2543.0,1.05,10922.72,11249.33,51.17,55.65
Инструменты,32286241,6059,5204,7229,1.19,5328.64,6204.12,19994966.0,4090.0,3822.0,4839.0,1.18,4888.74,5231.55,61.93,66.94
Тренажеры,31368026,2382,2128,2498,1.05,13168.78,14740.61,19576596.0,1694.0,1665.0,1738.0,1.03,11556.43,11757.72,62.41,69.58
Периферийные устройства,30766796,3423,3034,3719,1.09,8988.25,10140.67,20406951.0,2409.0,2308.0,2544.0,1.06,8471.13,8841.83,66.33,68.41
Сантехника,22623791,3661,3054,5368,1.47,6179.68,7407.92,14993215.0,2620.0,2409.0,3921.0,1.50,5722.60,6223.83,66.27,73.04
Планшеты,21191531,1773,1560,1955,1.10,11952.36,13584.31,10703948.0,1041.0,1000.0,1113.0,1.07,10282.37,10703.95,50.51,56.93
Красота и здоровье,20003641,7139,6123,7724,1.08,2802.02,3266.97,13125475.0,4957.0,4636.0,5166.0,1.04,2647.87,2831.21,65.62,66.88
Фотоаппараты,19237778,890,777,1004,1.13,21615.48,24759.05,9478070.0,515.0,494.0,570.0,1.11,18404.02,19186.38,49.27,56.77
Офис и Кабинет,15244695,2581,2268,3014,1.17,5906.51,6721.65,11000751.0,1935.0,1899.0,2205.0,1.14,5685.14,5792.92,72.16,73.16

In [13]:
join

,Revenue total,Orders total,Clients total,Goods total,Avg goods,Average bill total,Avg client,Revenue redeemed,Order_ID_sold,Phone_new_sold,Goods redeemed,Avg goods_sold,Avg order_sold,Avg client_sold,Revenue redeemability,Goods redeemability
TK,,,,,,,,,,,,,,,,
Телевизоры LCD,226948918,7478,5382,7767,1.04,30348.88,42168.14,120590672.0,4485.0,3541.0,4595.0,1.02,26887.55,34055.54,53.14,59.16
Мобильные средства связи,202208122,10668,9093,11273,1.06,18954.64,22237.78,66398080.0,4956.0,4732.0,5217.0,1.05,13397.51,14031.72,32.84,46.28
Холодильное оборудование,191429362,7807,6152,8063,1.03,24520.22,31116.61,119899953.0,5215.0,4586.0,5337.0,1.02,22991.36,26144.78,62.63,66.19
Встраиваемая техника,183478346,9323,6855,10821,1.16,19680.18,26765.62,115362638.0,6140.0,5178.0,7099.0,1.16,18788.70,22279.38,62.88,65.60
Стиральные машины,119682526,5608,4274,5727,1.02,21341.39,28002.46,73728741.0,3601.0,3080.0,3629.0,1.01,20474.52,23937.90,61.60,63.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Материалы для инсталляции,6270,1,1,30,30.00,6270.00,6270.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Ванна, баня и сауна",4218,6,6,6,1.00,703.00,703.00,4218.0,6.0,6.0,6.0,1.00,703.00,703.00,100.00,100.00
Подарки КБТ,241,12,8,20,1.67,20.08,30.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Товары для дома и офиса,35,1,1,1,1.00,35.00,35.00,35.0,1.0,1.0,1.0,1.00,35.00,35.00,100.00,100.00
Упаковка,27,3,3,3,1.00,9.00,9.00,18.0,2.0,2.0,2.0,1.00,9.00,9.00,66.67,66.67